# config.toml
[umu]
prefix = "~/Lutris-Prefixes/still-wakes-the-deep"
proton = "~/.local/share/Steam/compatibilitytools.d/GE-Proton9-20"
game_id = "umu-1622910"
exe = "~/Games/Still Wakes the Deep/Habitat/Binaries/Win64/StillWakesTheDeep.exe"
launch_args = [ "-SkipBuildPatchPrereq" ]
store = "steam"

#WINEPREFIX=/home/zerohack/Lutris-Prefixes/GTA-IV GAMEID=0 PROTONPATH=GE-Proton umu-run "/home/zerohack/Games/Grand Theft Auto IV - The Complete Edition/GTAIV.exe"
#launch_args = ["-opengl", "-SkipBuildPatchPrereq"]
