# Start on boot
exec-once = awww-daemon
#exec-once = sleep 1 && bash $HOME/.config/Scripts/random_wall_on_home.sh
exec-once = foot --server
exec-once = blueman-applet >/dev/null 2>&1 &
exec-once = "awww img ~/.config/niri/wall.jpg --transition-type any --transition-step 5 --transition-fps 165 --transition-duration 2"
exec-once = "mpd"
exec-once = "mpDris2"
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
exec-once = wl-paste --type image --watch cliphist store
exec-once = wl-paste --type text --watch cliphist store
exec-once = "kitty -1 --session <(echo 'launch --allow-remote-control --hold kitten @ resize-os-window --action=hide')"
# exec-once = sleep 3 && paplay /usr/share/sounds/freedesktop/stereo/message.oga|notify-send --icon ~/.config/Resources/images/PFP.jpg "Welcome back" $USER
# exec-once = waybar -c $HOME/.config/waybar/MangoWC/config.jsonc -s $HOME/.config/waybar/style.css
# exec-once = swayidle -w timeout 300 'systemctl suspend' before-sleep 'hyprlock'
